version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of your Python project
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/" # Location of your GitHub Actions workflows
    schedule:
      interval: "weekly"
